### ISSUE TITLE
capture_image err

### ISSUE THREAD

**Issue by TheDigitalCat** [bitcraft/shutter#2]
zz@zz-N56JN:~$ python
Python 3.6.5 (default, Jun 11 2018, 23:03:46)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
>>> import shutter
>>> camera = shutter.Camera()
>>> camera.capture_image("my_pic.jpg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zz/.pyenv/versions/booth3.6/lib/python3.6/site-packages/shutter/shutter.py", line 345, in capture_image
    self.download_and_save(path.folder, path.name, destpath)
  File "/home/zz/.pyenv/versions/booth3.6/lib/python3.6/site-packages/shutter/shutter.py", line 387, in download_and_save
    srcfolder = srcfolder.encode('ascii')
AttributeError: 'bytes' object has no attribute 'encode'

```

**Comment by bitcraft** [comment]
Unfortunately, I had some issues with this library and haven't updated it in a long time.  You could try removing `.encode('ascii')` from the library source and try again.  I just don't have the time recently to address issues like this, sorry!  :(
